db_gear = [
    {
        "id": 2,
        "quality": "2",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Backpack",
        "type": "Acosta's Go-Bag",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Skill Tier",
        "attr2": "Skill Haste",
        "mod": "Skill Damage",
        "talent": "U"
    },
    {
        "id": 3,
        "quality": "N3",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Gloves",
        "type": "Bloody Knuckles",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Weapon damage 1.5% - 15%",
        "attr2": "Critical Hit Chance 1.2% - 6%",
        "mod": "Critical Hit Damage 6% - 12%",
        "talent": ""
    },
    {
        "id": 4,
        "quality": "3",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Gloves",
        "type": "BTSU Gloves",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Skill Tier",
        "attr2": "Skill Haste",
        "mod": "Repair Skills",
        "talent": ""
    },
    {
        "id": 5,
        "quality": "N5",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Mask",
        "type": "Catharsis",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "\"Armour 16,594 - 170,000\"",
        "attr2": "Incoming Repair 7.8% - 20%",
        "mod": "Armor Regen 1689 - 4925",
        "talent": ""
    },
    {
        "id": 6,
        "quality": "4",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Mask",
        "type": "Coyote's Mask",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Weapon Damage",
        "attr2": "Critical Hit Chance",
        "mod": "Critical Hit Damage",
        "talent": "O"
    },
    {
        "id": 7,
        "quality": "5",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Holster",
        "type": "Dodge City Gunslinger's Holster",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Weapon Damage",
        "attr2": "Weapon Handling",
        "mod": "Headshot Damage",
        "talent": ""
    },
    {
        "id": 8,
        "quality": "6",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Holster",
        "type": "Imperial Dynasty",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Skill Tier",
        "attr2": "Status Effects",
        "mod": "Hazard Protection",
        "talent": ""
    },
    {
        "id": 9,
        "quality": "N1",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Backpack",
        "type": "Memento",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Weapon damage 1.5% - 15%",
        "attr2": "\"Armour 16,594 - 170,000\"",
        "mod": ">+1< Skill tier",
        "talent": ""
    },
    {
        "id": 10,
        "quality": "N2",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Backpack",
        "type": "NinjaBike Messenger Backpack",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Weapon damage 1.5% - 15%",
        "attr2": "\"Armour 16,594 - 170,000\"",
        "mod": ">+1< Skill tier",
        "talent": ""
    },
    {
        "id": 11,
        "quality": "7",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Kneepads",
        "type": "NinjaBike Messenger Kneepads",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Weapon Damage",
        "attr2": "Critical Hit Chance",
        "mod": "Critical Hit Damage",
        "talent": ""
    },
    {
        "id": 12,
        "quality": "N8",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Chest",
        "type": "Ridgeway's Pride",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Weapon damage 1.5% - 15%",
        "attr2": "Critical Hit Chance 1.2% - 6%",
        "mod": "Critical Hit Damage 6% - 12%",
        "talent": ""
    },
    {
        "id": 13,
        "quality": "8",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Kneepads",
        "type": "Sawyer's Kneepads",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Armor",
        "attr2": "Explosive Resistance",
        "mod": "Health",
        "talent": ""
    },
    {
        "id": 14,
        "quality": "N6",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Holster",
        "type": "Shocker Punch",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "\"Armour 16,594 - 170.000\"",
        "attr2": "Explosive Resist 1% - 10%",
        "mod": "Hazard Protection 5% - 10%",
        "talent": ""
    },
    {
        "id": 15,
        "quality": "9",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Chest",
        "type": "Tardigrade Armor System",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": "Armor",
        "attr2": "Explosive Resistance",
        "mod": "Armor Regeneration",
        "talent": "D"
    },
    {
        "id": 16,
        "quality": "N4",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Mask",
        "type": "Vile",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": ">+1< Skill tier",
        "attr2": "Status Effect 5% - 10%",
        "mod": "Hazard Protection 5% - 10%",
        "talent": ""
    },
    {
        "id": 17,
        "quality": "N7",
        "slot": "Exotic",
        "class": "Exotic",
        "item": "Holster",
        "type": "Waveform",
        "brand_num": "E",
        "brand": "1",
        "core": "Exotic",
        "attr1": ">+1< Skill tier",
        "attr2": "Skill Damage",
        "mod": "Skill Haste",
        "talent": ""
    },
    {
        "id": 18,
        "quality": "17",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Aces and Eights",
        "brand_num": "S",
        "brand": "",
        "core": "Aces and Eights",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 19,
        "quality": "18",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Aces and Eights",
        "brand_num": "S",
        "brand": "",
        "core": "Aces and Eights",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 20,
        "quality": "19",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Aces and Eights",
        "brand_num": "S",
        "brand": "",
        "core": "Aces and Eights",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 21,
        "quality": "20",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Aces and Eights",
        "brand_num": "S",
        "brand": "",
        "core": "Aces and Eights",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 22,
        "quality": "21",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Aces and Eights",
        "brand_num": "S",
        "brand": "",
        "core": "Aces and Eights",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 23,
        "quality": "22",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Aces and Eights",
        "brand_num": "S",
        "brand": "",
        "core": "Aces and Eights",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 24,
        "quality": "GS1",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Eclipse Protocol",
        "brand_num": "S",
        "brand": "",
        "core": "Eclipse Protocol",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 25,
        "quality": "GS2",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Eclipse Protocol",
        "brand_num": "S",
        "brand": "",
        "core": "Eclipse Protocol",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 26,
        "quality": "GS3",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Eclipse Protocol",
        "brand_num": "S",
        "brand": "",
        "core": "Eclipse Protocol",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 27,
        "quality": "GS4",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Eclipse Protocol",
        "brand_num": "S",
        "brand": "",
        "core": "Eclipse Protocol",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 28,
        "quality": "GS5",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Eclipse Protocol",
        "brand_num": "S",
        "brand": "",
        "core": "Eclipse Protocol",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 29,
        "quality": "GS6",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Eclipse Protocol",
        "brand_num": "S",
        "brand": "",
        "core": "Eclipse Protocol",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 30,
        "quality": "74",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Foundry Bullwark",
        "brand_num": "S",
        "brand": "",
        "core": "Foundry Bullwark",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 31,
        "quality": "75",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Foundry Bullwark",
        "brand_num": "S",
        "brand": "",
        "core": "Foundry Bullwark",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 32,
        "quality": "76",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Foundry Bullwark",
        "brand_num": "S",
        "brand": "",
        "core": "Foundry Bullwark",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 33,
        "quality": "77",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Foundry Bullwark",
        "brand_num": "S",
        "brand": "",
        "core": "Foundry Bullwark",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 34,
        "quality": "78",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Foundry Bullwark",
        "brand_num": "S",
        "brand": "",
        "core": "Foundry Bullwark",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 35,
        "quality": "79",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Foundry Bullwark",
        "brand_num": "S",
        "brand": "",
        "core": "Foundry Bullwark",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 36,
        "quality": "80",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Future Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Future Initiative",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 37,
        "quality": "81",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Future Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Future Initiative",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 38,
        "quality": "82",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Future Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Future Initiative",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 39,
        "quality": "83",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Future Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Future Initiative",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 40,
        "quality": "84",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Future Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Future Initiative",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 41,
        "quality": "85",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Future Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Future Initiative",
        "attr1": "N/A",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 42,
        "quality": "116",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Hard Wired",
        "brand_num": "S",
        "brand": "",
        "core": "Hard Wired",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 43,
        "quality": "117",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Hard Wired",
        "brand_num": "S",
        "brand": "",
        "core": "Hard Wired",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 44,
        "quality": "118",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Hard Wired",
        "brand_num": "S",
        "brand": "",
        "core": "Hard Wired",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 45,
        "quality": "119",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Hard Wired",
        "brand_num": "S",
        "brand": "",
        "core": "Hard Wired",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 46,
        "quality": "120",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Hard Wired",
        "brand_num": "S",
        "brand": "",
        "core": "Hard Wired",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 47,
        "quality": "121",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Hard Wired",
        "brand_num": "S",
        "brand": "",
        "core": "Hard Wired",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 48,
        "quality": "GS7",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Heartbreaker",
        "brand_num": "S",
        "brand": "",
        "core": "Heartbreaker",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 49,
        "quality": "GS8",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Heartbreaker",
        "brand_num": "S",
        "brand": "",
        "core": "Heartbreaker",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 50,
        "quality": "GS9",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Heartbreaker",
        "brand_num": "S",
        "brand": "",
        "core": "Heartbreaker",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 51,
        "quality": "GS10",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Heartbreaker",
        "brand_num": "S",
        "brand": "",
        "core": "Heartbreaker",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 52,
        "quality": "GS11",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Heartbreaker",
        "brand_num": "S",
        "brand": "",
        "core": "Heartbreaker",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 53,
        "quality": "GS12",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Heartbreaker",
        "brand_num": "S",
        "brand": "",
        "core": "Heartbreaker",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 54,
        "quality": "GS13",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Hotshot",
        "brand_num": "S",
        "brand": "",
        "core": "Hotshot",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 55,
        "quality": "GS14",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Hotshot",
        "brand_num": "S",
        "brand": "",
        "core": "Hotshot",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 56,
        "quality": "GS15",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Hotshot",
        "brand_num": "S",
        "brand": "",
        "core": "Hotshot",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 57,
        "quality": "GS16",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Hotshot",
        "brand_num": "S",
        "brand": "",
        "core": "Hotshot",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 58,
        "quality": "GS17",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Hotshot",
        "brand_num": "S",
        "brand": "",
        "core": "Hotshot",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 59,
        "quality": "GS18",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Hotshot",
        "brand_num": "S",
        "brand": "",
        "core": "Hotshot",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 60,
        "quality": "GS19",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Hunter's Fury",
        "brand_num": "S",
        "brand": "",
        "core": "Hunter's Fury",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 61,
        "quality": "GS20",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Hunter's Fury",
        "brand_num": "S",
        "brand": "",
        "core": "Hunter's Fury",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 62,
        "quality": "GS21",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Hunter's Fury",
        "brand_num": "S",
        "brand": "",
        "core": "Hunter's Fury",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 63,
        "quality": "GS22",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Hunter's Fury",
        "brand_num": "S",
        "brand": "",
        "core": "Hunter's Fury",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 64,
        "quality": "GS23",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Hunter's Fury",
        "brand_num": "S",
        "brand": "",
        "core": "Hunter's Fury",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 65,
        "quality": "GS24",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Hunter's Fury",
        "brand_num": "S",
        "brand": "",
        "core": "Hunter's Fury",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 66,
        "quality": "129",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Negotiator's Dilemma",
        "brand_num": "S",
        "brand": "",
        "core": "Negotiator's Dilemma",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 67,
        "quality": "130",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Negotiator's Dilemma",
        "brand_num": "S",
        "brand": "",
        "core": "Negotiator's Dilemma",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 68,
        "quality": "131",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Negotiator's Dilemma",
        "brand_num": "S",
        "brand": "",
        "core": "Negotiator's Dilemma",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 69,
        "quality": "132",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Negotiator's Dilemma",
        "brand_num": "S",
        "brand": "",
        "core": "Negotiator's Dilemma",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 70,
        "quality": "133",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Negotiator's Dilemma",
        "brand_num": "S",
        "brand": "",
        "core": "Negotiator's Dilemma",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 71,
        "quality": "134",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Negotiator's Dilemma",
        "brand_num": "S",
        "brand": "",
        "core": "Negotiator's Dilemma",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 72,
        "quality": "135",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Ongoing Directive",
        "brand_num": "S",
        "brand": "",
        "core": "Ongoing Directive",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 73,
        "quality": "136",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Ongoing Directive",
        "brand_num": "S",
        "brand": "",
        "core": "Ongoing Directive",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 74,
        "quality": "137",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Ongoing Directive",
        "brand_num": "S",
        "brand": "",
        "core": "Ongoing Directive",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 75,
        "quality": "138",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Ongoing Directive",
        "brand_num": "S",
        "brand": "",
        "core": "Ongoing Directive",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 76,
        "quality": "139",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Ongoing Directive",
        "brand_num": "S",
        "brand": "",
        "core": "Ongoing Directive",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 77,
        "quality": "140",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Ongoing Directive",
        "brand_num": "S",
        "brand": "",
        "core": "Ongoing Directive",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 78,
        "quality": "141",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Overlord Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Overlord Armaments",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 79,
        "quality": "GS25",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Rigger",
        "brand_num": "S",
        "brand": "",
        "core": "Rigger",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 80,
        "quality": "GS26",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Rigger",
        "brand_num": "S",
        "brand": "",
        "core": "Rigger",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 81,
        "quality": "GS27",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Rigger",
        "brand_num": "S",
        "brand": "",
        "core": "Rigger",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 82,
        "quality": "GS28",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Rigger",
        "brand_num": "S",
        "brand": "",
        "core": "Rigger",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 83,
        "quality": "GS29",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Rigger",
        "brand_num": "S",
        "brand": "",
        "core": "Rigger",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 84,
        "quality": "GS30",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Rigger",
        "brand_num": "S",
        "brand": "",
        "core": "Rigger",
        "attr1": "Skill Tier",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 85,
        "quality": "178",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Striker's Battlegear",
        "brand_num": "S",
        "brand": "",
        "core": "Striker's Battlegear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 86,
        "quality": "179",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Striker's Battlegear",
        "brand_num": "S",
        "brand": "",
        "core": "Striker's Battlegear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 87,
        "quality": "180",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Striker's Battlegear",
        "brand_num": "S",
        "brand": "",
        "core": "Striker's Battlegear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 88,
        "quality": "181",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Striker's Battlegear",
        "brand_num": "S",
        "brand": "",
        "core": "Striker's Battlegear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 89,
        "quality": "182",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Striker's Battlegear",
        "brand_num": "S",
        "brand": "",
        "core": "Striker's Battlegear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 90,
        "quality": "183",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Striker's Battlegear",
        "brand_num": "S",
        "brand": "",
        "core": "Striker's Battlegear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 91,
        "quality": "184",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "System Corruption",
        "brand_num": "S",
        "brand": "",
        "core": "System Corruption",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 92,
        "quality": "185",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "System Corruption",
        "brand_num": "S",
        "brand": "",
        "core": "System Corruption",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 93,
        "quality": "186",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "System Corruption",
        "brand_num": "S",
        "brand": "",
        "core": "System Corruption",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 94,
        "quality": "187",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "System Corruption",
        "brand_num": "S",
        "brand": "",
        "core": "System Corruption",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 95,
        "quality": "188",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "System Corruption",
        "brand_num": "S",
        "brand": "",
        "core": "System Corruption",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 96,
        "quality": "189",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "System Corruption",
        "brand_num": "S",
        "brand": "",
        "core": "System Corruption",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 97,
        "quality": "GS31",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "The Cavalier",
        "brand_num": "S",
        "brand": "",
        "core": "The Cavalier",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 98,
        "quality": "GS32",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "The Cavalier",
        "brand_num": "S",
        "brand": "",
        "core": "The Cavalier",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 99,
        "quality": "GS33",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "The Cavalier",
        "brand_num": "S",
        "brand": "",
        "core": "The Cavalier",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 100,
        "quality": "GS34",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "The Cavalier",
        "brand_num": "S",
        "brand": "",
        "core": "The Cavalier",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 101,
        "quality": "GS35",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "The Cavalier",
        "brand_num": "S",
        "brand": "",
        "core": "The Cavalier",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 102,
        "quality": "GS36",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "The Cavalier",
        "brand_num": "S",
        "brand": "",
        "core": "The Cavalier",
        "attr1": "Armor",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 103,
        "quality": "190",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Tip of the Spear",
        "brand_num": "S",
        "brand": "",
        "core": "Tip of the Spear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 104,
        "quality": "191",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Tip of the Spear",
        "brand_num": "S",
        "brand": "",
        "core": "Tip of the Spear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 105,
        "quality": "192",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Tip of the Spear",
        "brand_num": "S",
        "brand": "",
        "core": "Tip of the Spear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 106,
        "quality": "193",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Tip of the Spear",
        "brand_num": "S",
        "brand": "",
        "core": "Tip of the Spear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 107,
        "quality": "194",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Tip of the Spear",
        "brand_num": "S",
        "brand": "",
        "core": "Tip of the Spear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 108,
        "quality": "195",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Tip of the Spear",
        "brand_num": "S",
        "brand": "",
        "core": "Tip of the Spear",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 109,
        "quality": "196",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "True Patriot",
        "brand_num": "S",
        "brand": "",
        "core": "True Patriot",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 110,
        "quality": "197",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "True Patriot",
        "brand_num": "S",
        "brand": "",
        "core": "True Patriot",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 111,
        "quality": "198",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "True Patriot",
        "brand_num": "S",
        "brand": "",
        "core": "True Patriot",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 112,
        "quality": "199",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "True Patriot",
        "brand_num": "S",
        "brand": "",
        "core": "True Patriot",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 113,
        "quality": "200",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "True Patriot",
        "brand_num": "S",
        "brand": "",
        "core": "True Patriot",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 114,
        "quality": "201",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "True Patriot",
        "brand_num": "S",
        "brand": "",
        "core": "True Patriot",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 115,
        "quality": "GS37",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Backpack",
        "type": "Umbra Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Umbra Initiative",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 116,
        "quality": "GS38",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Chest",
        "type": "Umbra Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Umbra Initiative",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 117,
        "quality": "GS39",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Gloves",
        "type": "Umbra Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Umbra Initiative",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 118,
        "quality": "GS40",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Holster",
        "type": "Umbra Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Umbra Initiative",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 119,
        "quality": "GS41",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Kneepads",
        "type": "Umbra Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Umbra Initiative",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 120,
        "quality": "GS42",
        "slot": "Gearset",
        "class": "Gearset",
        "item": "Mask",
        "type": "Umbra Initiative",
        "brand_num": "S",
        "brand": "",
        "core": "Umbra Initiative",
        "attr1": "Weapon Damage",
        "attr2": "",
        "mod": "",
        "talent": ""
    },
    {
        "id": 121,
        "quality": "10",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "5.11 Tactical",
        "brand_num": "A",
        "brand": "",
        "core": "5.11 Tactical",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 122,
        "quality": "11",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "5.11 Tactical",
        "brand_num": "A",
        "brand": "",
        "core": "5.11 Tactical",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 123,
        "quality": "12",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "5.11 Tactical",
        "brand_num": "A",
        "brand": "",
        "core": "5.11 Tactical",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 124,
        "quality": "13",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "5.11 Tactical",
        "brand_num": "A",
        "brand": "",
        "core": "5.11 Tactical",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 125,
        "quality": "14",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "5.11 Tactical",
        "brand_num": "A",
        "brand": "",
        "core": "5.11 Tactical",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 126,
        "quality": "15",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "5.11 Tactical",
        "brand_num": "A",
        "brand": "",
        "core": "5.11 Tactical",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 127,
        "quality": "23",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Airaldi Holdings",
        "brand_num": "A",
        "brand": "",
        "core": "Airaldi Holdings",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 128,
        "quality": "24",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Airaldi Holdings",
        "brand_num": "A",
        "brand": "",
        "core": "Airaldi Holdings",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 129,
        "quality": "25",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Airaldi Holdings",
        "brand_num": "A",
        "brand": "",
        "core": "Airaldi Holdings",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 130,
        "quality": "26",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Airaldi Holdings",
        "brand_num": "A",
        "brand": "",
        "core": "Airaldi Holdings",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 131,
        "quality": "27",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Airaldi Holdings",
        "brand_num": "A",
        "brand": "",
        "core": "Airaldi Holdings",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 132,
        "quality": "28",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Airaldi Holdings",
        "brand_num": "A",
        "brand": "",
        "core": "Airaldi Holdings",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 133,
        "quality": "30",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Alps Summit Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Alps Summit Armaments",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 134,
        "quality": "31",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Alps Summit Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Alps Summit Armaments",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 135,
        "quality": "32",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Alps Summit Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Alps Summit Armaments",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 136,
        "quality": "33",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Alps Summit Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Alps Summit Armaments",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 137,
        "quality": "34",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Alps Summit Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Alps Summit Armaments",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 138,
        "quality": "35",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Alps Summit Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Alps Summit Armaments",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 139,
        "quality": "38",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Badger Tuff",
        "brand_num": "A",
        "brand": "",
        "core": "Badger Tuff",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 140,
        "quality": "39",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Badger Tuff",
        "brand_num": "A",
        "brand": "",
        "core": "Badger Tuff",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 141,
        "quality": "40",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Badger Tuff",
        "brand_num": "A",
        "brand": "",
        "core": "Badger Tuff",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 142,
        "quality": "41",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Badger Tuff",
        "brand_num": "A",
        "brand": "",
        "core": "Badger Tuff",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 143,
        "quality": "42",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Badger Tuff",
        "brand_num": "A",
        "brand": "",
        "core": "Badger Tuff",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 144,
        "quality": "43",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Badger Tuff",
        "brand_num": "A",
        "brand": "",
        "core": "Badger Tuff",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 145,
        "quality": "46",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Ceska Vyroba s.r.o.",
        "brand_num": "A",
        "brand": "",
        "core": "Ceska Vyroba s.r.o.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 146,
        "quality": "47",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Ceska Vyroba s.r.o.",
        "brand_num": "A",
        "brand": "",
        "core": "Ceska Vyroba s.r.o.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 147,
        "quality": "48",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Ceska Vyroba s.r.o.",
        "brand_num": "A",
        "brand": "",
        "core": "Ceska Vyroba s.r.o.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 148,
        "quality": "49",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Ceska Vyroba s.r.o.",
        "brand_num": "A",
        "brand": "",
        "core": "Ceska Vyroba s.r.o.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 149,
        "quality": "50",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Ceska Vyroba s.r.o.",
        "brand_num": "A",
        "brand": "",
        "core": "Ceska Vyroba s.r.o.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 150,
        "quality": "51",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Ceska Vyroba s.r.o.",
        "brand_num": "A",
        "brand": "",
        "core": "Ceska Vyroba s.r.o.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 151,
        "quality": "53",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "China Light Industries Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "China Light Industries Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 152,
        "quality": "54",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "China Light Industries Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "China Light Industries Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 153,
        "quality": "55",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "China Light Industries Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "China Light Industries Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 154,
        "quality": "56",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "China Light Industries Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "China Light Industries Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 155,
        "quality": "57",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "China Light Industries Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "China Light Industries Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 156,
        "quality": "58",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "China Light Industries Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "China Light Industries Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 157,
        "quality": "60",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Douglas & Harding",
        "brand_num": "A",
        "brand": "",
        "core": "Douglas & Harding",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 158,
        "quality": "61",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Douglas & Harding",
        "brand_num": "A",
        "brand": "",
        "core": "Douglas & Harding",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 159,
        "quality": "62",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Douglas & Harding",
        "brand_num": "A",
        "brand": "",
        "core": "Douglas & Harding",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 160,
        "quality": "63",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Douglas & Harding",
        "brand_num": "A",
        "brand": "",
        "core": "Douglas & Harding",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 161,
        "quality": "64",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Douglas & Harding",
        "brand_num": "A",
        "brand": "",
        "core": "Douglas & Harding",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 162,
        "quality": "65",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Douglas & Harding",
        "brand_num": "A",
        "brand": "",
        "core": "Douglas & Harding",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 163,
        "quality": "67",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Fenris Group AB",
        "brand_num": "A",
        "brand": "",
        "core": "Fenris Group AB",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 164,
        "quality": "68",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Fenris Group AB",
        "brand_num": "A",
        "brand": "",
        "core": "Fenris Group AB",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 165,
        "quality": "69",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Fenris Group AB",
        "brand_num": "A",
        "brand": "",
        "core": "Fenris Group AB",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 166,
        "quality": "70",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Fenris Group AB",
        "brand_num": "A",
        "brand": "",
        "core": "Fenris Group AB",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 167,
        "quality": "71",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Fenris Group AB",
        "brand_num": "A",
        "brand": "",
        "core": "Fenris Group AB",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 168,
        "quality": "72",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Fenris Group AB",
        "brand_num": "A",
        "brand": "",
        "core": "Fenris Group AB",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 169,
        "quality": "86",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Gila Guard",
        "brand_num": "A",
        "brand": "",
        "core": "Gila Guard",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 170,
        "quality": "87",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Gila Guard",
        "brand_num": "A",
        "brand": "",
        "core": "Gila Guard",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 171,
        "quality": "88",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Gila Guard",
        "brand_num": "A",
        "brand": "",
        "core": "Gila Guard",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 172,
        "quality": "89",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Gila Guard",
        "brand_num": "A",
        "brand": "",
        "core": "Gila Guard",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 173,
        "quality": "90",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Gila Guard",
        "brand_num": "A",
        "brand": "",
        "core": "Gila Guard",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 174,
        "quality": "91",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Gila Guard",
        "brand_num": "A",
        "brand": "",
        "core": "Gila Guard",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 175,
        "quality": "94",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Golan Gear Ltd",
        "brand_num": "A",
        "brand": "",
        "core": "Golan Gear Ltd",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 176,
        "quality": "95",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Golan Gear Ltd",
        "brand_num": "A",
        "brand": "",
        "core": "Golan Gear Ltd",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 177,
        "quality": "96",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Golan Gear Ltd",
        "brand_num": "A",
        "brand": "",
        "core": "Golan Gear Ltd",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 178,
        "quality": "97",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Golan Gear Ltd",
        "brand_num": "A",
        "brand": "",
        "core": "Golan Gear Ltd",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 179,
        "quality": "98",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Golan Gear Ltd",
        "brand_num": "A",
        "brand": "",
        "core": "Golan Gear Ltd",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 180,
        "quality": "99",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Golan Gear Ltd",
        "brand_num": "A",
        "brand": "",
        "core": "Golan Gear Ltd",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 181,
        "quality": "102",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Grupo Sombra S.A.",
        "brand_num": "A",
        "brand": "",
        "core": "Grupo Sombra S.A.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 182,
        "quality": "103",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Grupo Sombra S.A.",
        "brand_num": "A",
        "brand": "",
        "core": "Grupo Sombra S.A.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 183,
        "quality": "104",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Grupo Sombra S.A.",
        "brand_num": "A",
        "brand": "",
        "core": "Grupo Sombra S.A.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 184,
        "quality": "105",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Grupo Sombra S.A.",
        "brand_num": "A",
        "brand": "",
        "core": "Grupo Sombra S.A.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 185,
        "quality": "106",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Grupo Sombra S.A.",
        "brand_num": "A",
        "brand": "",
        "core": "Grupo Sombra S.A.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 186,
        "quality": "107",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Grupo Sombra S.A.",
        "brand_num": "A",
        "brand": "",
        "core": "Grupo Sombra S.A.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 187,
        "quality": "109",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Hana-U Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "Hana-U Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 188,
        "quality": "110",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Hana-U Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "Hana-U Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 189,
        "quality": "111",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Hana-U Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "Hana-U Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 190,
        "quality": "112",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Hana-U Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "Hana-U Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 191,
        "quality": "113",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Hana-U Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "Hana-U Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 192,
        "quality": "114",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Hana-U Corporation",
        "brand_num": "A",
        "brand": "",
        "core": "Hana-U Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 193,
        "quality": "216",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Improvised Holster",
        "brand_num": "A",
        "brand": "",
        "core": "Crafted",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 194,
        "quality": "122",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Murakami Industries",
        "brand_num": "A",
        "brand": "",
        "core": "Murakami Industries",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 195,
        "quality": "123",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Murakami Industries",
        "brand_num": "A",
        "brand": "",
        "core": "Murakami Industries",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 196,
        "quality": "124",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Murakami Industries",
        "brand_num": "A",
        "brand": "",
        "core": "Murakami Industries",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 197,
        "quality": "125",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Murakami Industries",
        "brand_num": "A",
        "brand": "",
        "core": "Murakami Industries",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 198,
        "quality": "126",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Murakami Industries",
        "brand_num": "A",
        "brand": "",
        "core": "Murakami Industries",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 199,
        "quality": "127",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Murakami Industries",
        "brand_num": "A",
        "brand": "",
        "core": "Murakami Industries",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 200,
        "quality": "142",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Overlord Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Overlord Armaments",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 201,
        "quality": "143",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Overlord Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Overlord Armaments",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 202,
        "quality": "144",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Overlord Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Overlord Armaments",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 203,
        "quality": "145",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Overlord Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Overlord Armaments",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 204,
        "quality": "146",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Overlord Armaments",
        "brand_num": "A",
        "brand": "",
        "core": "Overlord Armaments",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 205,
        "quality": "148",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Petrov Defense Group",
        "brand_num": "A",
        "brand": "",
        "core": "Petrov Defense Group",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 206,
        "quality": "149",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Petrov Defense Group",
        "brand_num": "A",
        "brand": "",
        "core": "Petrov Defense Group",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 207,
        "quality": "150",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Petrov Defense Group",
        "brand_num": "A",
        "brand": "",
        "core": "Petrov Defense Group",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 208,
        "quality": "151",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Petrov Defense Group",
        "brand_num": "A",
        "brand": "",
        "core": "Petrov Defense Group",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 209,
        "quality": "152",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Petrov Defense Group",
        "brand_num": "A",
        "brand": "",
        "core": "Petrov Defense Group",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 210,
        "quality": "153",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Petrov Defense Group",
        "brand_num": "A",
        "brand": "",
        "core": "Petrov Defense Group",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 211,
        "quality": "156",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Providence Defense",
        "brand_num": "A",
        "brand": "",
        "core": "Providence Defense",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 212,
        "quality": "157",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Providence Defense",
        "brand_num": "A",
        "brand": "",
        "core": "Providence Defense",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 213,
        "quality": "158",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Providence Defense",
        "brand_num": "A",
        "brand": "",
        "core": "Providence Defense",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 214,
        "quality": "159",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Providence Defense",
        "brand_num": "A",
        "brand": "",
        "core": "Providence Defense",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 215,
        "quality": "160",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Providence Defense",
        "brand_num": "A",
        "brand": "",
        "core": "Providence Defense",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 216,
        "quality": "161",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Providence Defense",
        "brand_num": "A",
        "brand": "",
        "core": "Providence Defense",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 217,
        "quality": "164",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Richter & Kaiser GmbH",
        "brand_num": "A",
        "brand": "",
        "core": "Richter & Kaiser GmbH",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 218,
        "quality": "165",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Richter & Kaiser GmbH",
        "brand_num": "A",
        "brand": "",
        "core": "Richter & Kaiser GmbH",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 219,
        "quality": "166",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Richter & Kaiser GmbH",
        "brand_num": "A",
        "brand": "",
        "core": "Richter & Kaiser GmbH",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 220,
        "quality": "167",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Richter & Kaiser GmbH",
        "brand_num": "A",
        "brand": "",
        "core": "Richter & Kaiser GmbH",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 221,
        "quality": "168",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Richter & Kaiser GmbH",
        "brand_num": "A",
        "brand": "",
        "core": "Richter & Kaiser GmbH",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 222,
        "quality": "169",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Richter & Kaiser GmbH",
        "brand_num": "A",
        "brand": "",
        "core": "Richter & Kaiser GmbH",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 223,
        "quality": "171",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Sokolov Concern",
        "brand_num": "A",
        "brand": "",
        "core": "Sokolov Concern",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 224,
        "quality": "172",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Sokolov Concern",
        "brand_num": "A",
        "brand": "",
        "core": "Sokolov Concern",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 225,
        "quality": "173",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Sokolov Concern",
        "brand_num": "A",
        "brand": "",
        "core": "Sokolov Concern",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 226,
        "quality": "174",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Sokolov Concern",
        "brand_num": "A",
        "brand": "",
        "core": "Sokolov Concern",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 227,
        "quality": "175",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Sokolov Concern",
        "brand_num": "A",
        "brand": "",
        "core": "Sokolov Concern",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 228,
        "quality": "176",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Sokolov Concern",
        "brand_num": "A",
        "brand": "",
        "core": "Sokolov Concern",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 229,
        "quality": "202",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Wyvern Wear",
        "brand_num": "A",
        "brand": "",
        "core": "Wyvern Wear",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 230,
        "quality": "203",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Wyvern Wear",
        "brand_num": "A",
        "brand": "",
        "core": "Wyvern Wear",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 231,
        "quality": "204",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Wyvern Wear",
        "brand_num": "A",
        "brand": "",
        "core": "Wyvern Wear",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 232,
        "quality": "205",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Wyvern Wear",
        "brand_num": "A",
        "brand": "",
        "core": "Wyvern Wear",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 233,
        "quality": "206",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Wyvern Wear",
        "brand_num": "A",
        "brand": "",
        "core": "Wyvern Wear",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 234,
        "quality": "207",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Wyvern Wear",
        "brand_num": "A",
        "brand": "",
        "core": "Wyvern Wear",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 235,
        "quality": "209",
        "slot": "High End",
        "class": "High End",
        "item": "Backpack",
        "type": "Yaahl Gear",
        "brand_num": "A",
        "brand": "",
        "core": "Yaahl Gear",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 236,
        "quality": "210",
        "slot": "High End",
        "class": "High End",
        "item": "Chest",
        "type": "Yaahl Gear",
        "brand_num": "A",
        "brand": "",
        "core": "Yaahl Gear",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 237,
        "quality": "211",
        "slot": "High End",
        "class": "High End",
        "item": "Gloves",
        "type": "Yaahl Gear",
        "brand_num": "A",
        "brand": "",
        "core": "Yaahl Gear",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 238,
        "quality": "212",
        "slot": "High End",
        "class": "High End",
        "item": "Holster",
        "type": "Yaahl Gear",
        "brand_num": "A",
        "brand": "",
        "core": "Yaahl Gear",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 239,
        "quality": "213",
        "slot": "High End",
        "class": "High End",
        "item": "Kneepads",
        "type": "Yaahl Gear",
        "brand_num": "A",
        "brand": "",
        "core": "Yaahl Gear",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 240,
        "quality": "214",
        "slot": "High End",
        "class": "High End",
        "item": "Mask",
        "type": "Yaahl Gear",
        "brand_num": "A",
        "brand": "",
        "core": "Yaahl Gear",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 241,
        "quality": "44",
        "slot": "Named",
        "class": "Named",
        "item": "Holster",
        "type": "Ammo Dump",
        "brand_num": "N",
        "brand": "",
        "core": "Badger Tuff",
        "attr1": "Armor",
        "attr2": "Ammo Capacity",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 242,
        "quality": "100",
        "slot": "Named",
        "class": "Named",
        "item": "Backpack",
        "type": "Anarchist's Cookbook",
        "brand_num": "N",
        "brand": "",
        "core": "Golan Gear Ltd",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 243,
        "quality": "208",
        "slot": "Named",
        "class": "Named",
        "item": "Holster",
        "type": "Claws Out",
        "brand_num": "N",
        "brand": "",
        "core": "Wyvern Wear",
        "attr1": "Pistol Damage",
        "attr2": "Melee Damage",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 244,
        "quality": "154",
        "slot": "Named",
        "class": "Named",
        "item": "Gloves",
        "type": "Contractor's Gloves",
        "brand_num": "N",
        "brand": "",
        "core": "Petrov Defense Group",
        "attr1": "Weapon Damage",
        "attr2": "Damage to Armor",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 245,
        "quality": "16",
        "slot": "Named",
        "class": "Named",
        "item": "Gloves",
        "type": "Deathgrips",
        "brand_num": "N",
        "brand": "",
        "core": "5.11 Tactical",
        "attr1": "Armor",
        "attr2": "Armor on Kill",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 246,
        "quality": "52",
        "slot": "Named",
        "class": "Named",
        "item": "Backpack",
        "type": "Devil's Due",
        "brand_num": "N",
        "brand": "",
        "core": "Ceska Vyroba s.r.o.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 247,
        "quality": "108",
        "slot": "Named",
        "class": "Named",
        "item": "Chest",
        "type": "Door-Kicker's Knock",
        "brand_num": "N",
        "brand": "",
        "core": "Grupo Sombra S.A.",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 248,
        "quality": "128",
        "slot": "Named",
        "class": "Named",
        "item": "Kneepads",
        "type": "Emperor's Guard",
        "brand_num": "N",
        "brand": "",
        "core": "Murakami Industries",
        "attr1": "Skill Tier",
        "attr2": "Armor Regeneration",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 249,
        "quality": "73",
        "slot": "Named",
        "class": "Named",
        "item": "Chest",
        "type": "Ferocious Calm",
        "brand_num": "N",
        "brand": "",
        "core": "Fenris Group AB",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 250,
        "quality": "177",
        "slot": "Named",
        "class": "Named",
        "item": "Gloves",
        "type": "Firm Handshake",
        "brand_num": "N",
        "brand": "",
        "core": "Sokolov Concern",
        "attr1": "Weapon Damage",
        "attr2": "Status Effects",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 251,
        "quality": "115",
        "slot": "Named",
        "class": "Named",
        "item": "Backpack",
        "type": "Force Multiplier",
        "brand_num": "N",
        "brand": "",
        "core": "Hana-U Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 252,
        "quality": "170",
        "slot": "Named",
        "class": "Named",
        "item": "Holster",
        "type": "Forge",
        "brand_num": "N",
        "brand": "",
        "core": "Richter & Kaiser GmbH",
        "attr1": "Skill Tier",
        "attr2": "Shield Health",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 253,
        "quality": "147",
        "slot": "Named",
        "class": "Named",
        "item": "Kneepads",
        "type": "Fox's Prayer",
        "brand_num": "N",
        "brand": "",
        "core": "Overlord Armaments",
        "attr1": "Weapon Damage",
        "attr2": "Damage to TOC",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 254,
        "quality": "101",
        "slot": "Named",
        "class": "Named",
        "item": "Chest",
        "type": "Hunter-Killer",
        "brand_num": "N",
        "brand": "",
        "core": "Golan Gear Ltd",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 255,
        "quality": "36",
        "slot": "Named",
        "class": "Named",
        "item": "Gloves",
        "type": "Motherly Love",
        "brand_num": "N",
        "brand": "",
        "core": "Alps Summit Armaments",
        "attr1": "Skill Tier",
        "attr2": "Skill Health",
        "mod": "A",
        "talent": ""
    },
    {
        "id": 256,
        "quality": "92",
        "slot": "Named",
        "class": "Named",
        "item": "Mask",
        "type": "Nightwatcher",
        "brand_num": "N",
        "brand": "",
        "core": "Gila Guard",
        "attr1": "Armor",
        "attr2": "Pulse Haste",
        "mod": "U",
        "talent": "D"
    },
    {
        "id": 257,
        "quality": "37",
        "slot": "Named",
        "class": "Named",
        "item": "Backpack",
        "type": "Percussive Maintenance",
        "brand_num": "N",
        "brand": "",
        "core": "Alps Summit Armaments",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 258,
        "quality": "93",
        "slot": "Named",
        "class": "Named",
        "item": "Chest",
        "type": "Pointman",
        "brand_num": "N",
        "brand": "",
        "core": "Gila Guard",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "D"
    },
    {
        "id": 259,
        "quality": "29",
        "slot": "Named",
        "class": "Named",
        "item": "Chest",
        "type": "Pristine Example",
        "brand_num": "N",
        "brand": "",
        "core": "Airaldi Holdings",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 260,
        "quality": "66",
        "slot": "Named",
        "class": "Named",
        "item": "Mask",
        "type": "Punch Drunk",
        "brand_num": "N",
        "brand": "",
        "core": "Douglas & Harding",
        "attr1": "Weapon Damage",
        "attr2": "Headshot Damage",
        "mod": "O",
        "talent": "O"
    },
    {
        "id": 261,
        "quality": "59",
        "slot": "Named",
        "class": "Named",
        "item": "Backpack",
        "type": "Strategic Alignment",
        "brand_num": "N",
        "brand": "",
        "core": "China Light Industries Corporation",
        "attr1": "Skill Tier",
        "attr2": "A",
        "mod": "A",
        "talent": "U"
    },
    {
        "id": 262,
        "quality": "162",
        "slot": "Named",
        "class": "Named",
        "item": "Backpack",
        "type": "The Gift",
        "brand_num": "N",
        "brand": "",
        "core": "Providence Defense",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 263,
        "quality": "215",
        "slot": "Named",
        "class": "Named",
        "item": "Mask",
        "type": "The Hollow Man",
        "brand_num": "N",
        "brand": "",
        "core": "Yaahl Gear",
        "attr1": "Armor",
        "attr2": "Damage to Health",
        "mod": "O",
        "talent": "O"
    },
    {
        "id": 264,
        "quality": "163",
        "slot": "Named",
        "class": "Named",
        "item": "Chest",
        "type": "The Sacrifice",
        "brand_num": "N",
        "brand": "",
        "core": "Providence Defense",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 265,
        "quality": "155",
        "slot": "Named",
        "class": "Named",
        "item": "Chest",
        "type": "Vedmedytsya Vest",
        "brand_num": "N",
        "brand": "",
        "core": "Petrov Defense Group",
        "attr1": "Weapon Damage",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    },
    {
        "id": 266,
        "quality": "45",
        "slot": "Named",
        "class": "Named",
        "item": "Chest",
        "type": "Zero F's",
        "brand_num": "N",
        "brand": "",
        "core": "Badger Tuff",
        "attr1": "Armor",
        "attr2": "A",
        "mod": "A",
        "talent": "O"
    }
]
